### ISSUE TITLE
Assertion error starting Phy2 for KS3 data

### ISSUE THREAD

**Issue by HiroyukiKato7** [MouseLand/Kilosort#355]
I'm not sure if this is related to #329, but I get an assertion error starting Phy2 for KS3 data.  The same recording data sorted with KS2 has no problem.  In case of #329, it seems that Phy2 at least opened, but in my case the Phy2 window does not even open.  The error message is as follows:

←[31m17:08:41.799 [E] __init__:62          An error has occurred (AssertionError):
Traceback (most recent call last):
  File "(path)\anaconda3\envs\phy2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "(path)\anaconda3\envs\phy2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "(path)\anaconda3\envs\phy2\Scripts\phy.exe\__main__.py", line 9, in <module>
    sys.exit(phycli())
  File "(path)\anaconda3\envs\phy2\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "(path)\anaconda3\envs\phy2\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "(path)\anaconda3\envs\phy2\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "(path)\anaconda3\envs\phy2\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "(path)\anaconda3\envs\phy2\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "(path)\anaconda3\envs\phy2\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "(path)\anaconda3\envs\phy2\lib\site-packages\phy\apps\__init__.py", line 136, in cli_template_gui
    template_gui(params_path, **kwargs)
  File "(path)\anaconda3\envs\phy2\lib\site-packages\phy\apps\template\gui.py", line 187, in template_gui
    controller = TemplateController(**get_template_params(params_path), **kwargs)
  File "(path)\anaconda3\envs\phy2\lib\site-packages\phy\apps\base.py", line 676, in __init__
    self.model = self._create_model(dir_path=dir_path, **kwargs) if model is None else model
  File "(path)\anaconda3\envs\phy2\lib\site-packages\phy\apps\template\gui.py", line 84, in _create_model
    return TemplateModel(dir_path=dir_path, **kwargs)
  File "(path)\anaconda3\envs\phy2\lib\site-packages\phylib\io\model.py", line 276, in __init__
    self._load_data()
  File "(path)\anaconda3\envs\phy2\lib\site-packages\phylib\io\model.py", line 312, in _load_data
    assert self.channel_positions.shape == (nc, 2)
AssertionError
←[0m

I would appreciate it if I could get help in resolving this issue.

Thanks

**Comment by HiroyukiKato7** [comment]
It seems that this happens when I exclude some channels for sorting.  I can open Phy when I use the whole 64 channels. (This is from Cambridge 64-ch linear probe recording)

**Comment by javierzsm** [comment]
hi, 
similar problem here using phy2 to load data produced by kilosort3 (updated on sept 03, 2021). I didn't have the problem before.

![assertion error phy2](https://user-images.githubusercontent.com/18037746/131999131-3dfee76b-2c67-4328-9cef-572aa2b1e9e4.png)
