### ISSUE TITLE
Undefined function 'spikedetector3' for input arguments of type 'gpuArray'.

### ISSUE THREAD

**Issue by Yambottle** [MouseLand/Kilosort#447]
# Environment
OS: `Ubuntu 20.04` | EC2: `p2.xlarge`
GPU: `Tesla K80`
NVIDIA Driver Version: `470.57.02`
CUDA Version: `11.4`
Kilosort: `3.0`(the latest main branch)
MATLAB: `R2021a`
gcc version: `9.3.0`

---

# Error Traceback
```
Traceback (most recent call last):
│  File "/home/ubuntu/anaconda3/envs/spike_sorting/lib/python3.7/runpy.py", line 193, in _run_module_as_main
│    "__main__", mod_spec)
│  File "/home/ubuntu/anaconda3/envs/spike_sorting/lib/python3.7/runpy.py", line 85, in _run_code
│    exec(code, run_globals)
│  File "/home/ubuntu/anaconda3/envs/spike_sorting/lib/python3.7/site-packages/ecephys_spike_sorting/modules/kilosort_helper/__main__.py", line 285, in <mod
│ule>
│    main()
│  File "/home/ubuntu/anaconda3/envs/spike_sorting/lib/python3.7/site-packages/ecephys_spike_sorting/modules/kilosort_helper/__main__.py", line 275, in main
│    output = run_kilosort(mod.args)
│  File "/home/ubuntu/anaconda3/envs/spike_sorting/lib/python3.7/site-packages/ecephys_spike_sorting/modules/kilosort_helper/__main__.py", line 130, in run_
│kilosort
│    nargout=0)
│  File "/home/ubuntu/anaconda3/envs/spike_sorting/lib/python3.7/site-packages/matlab/engine/matlabengine.py", line 71, in __call__
│    _stderr, feval=True).result()
│  File "/home/ubuntu/anaconda3/envs/spike_sorting/lib/python3.7/site-packages/matlab/engine/futureresult.py", line 67, in result
│    return self.__future.result(timeout)
│  File "/home/ubuntu/anaconda3/envs/spike_sorting/lib/python3.7/site-packages/matlab/engine/fevalfuture.py", line 82, in result
│    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
│matlab.engine.MatlabExecutionError:
│  File /home/ubuntu/neuropixel/Kilosort-3.0/preProcess/standalone_detector.m, line 63, in standalone_detector
│
│  File /home/ubuntu/neuropixel/Kilosort-3.0/preProcess/datashift2.m, line 58, in datashift2
│
│  File /home/ubuntu/neuropixel/data_for_ecephys/kilosort_datatemp/main_kilosort_multiversion.m, line 95, in main_kilosort_multiversion
│Undefined function 'spikedetector3' for input arguments of type 'gpuArray'.
```

---
# Full Log
```
|Channel-whitening matrix computed.
│Time  27s. Loading raw data and applying filters...
│Time 904s. Finished preprocessing 1335 batches.
│vertical pitch size is 20
│horizontal pitch size is 32
│    11    27    43    59
│
│   602
│
│Undefined function 'spikedetector3' for input arguments of type 'gpuArray'.
│
│Error in standalone_detector (line 63)
│    [dat, kkmax, st, cF] = spikedetector3(Params, dataRAW, wTEMP, iC-1, dist, v2, iC2-1, dist2);
│
│Error in datashift2 (line 58)
│[st3, rez] = standalone_detector(rez, spkTh);
│
│Error in main_kilosort_multiversion (line 95)
│    rez                = datashift2(rez, 1);
│
│Traceback (most recent call last):
│  File "/home/ubuntu/anaconda3/envs/spike_sorting/lib/python3.7/runpy.py", line 193, in _run_module_as_main
│    "__main__", mod_spec)
│  File "/home/ubuntu/anaconda3/envs/spike_sorting/lib/python3.7/runpy.py", line 85, in _run_code
│    exec(code, run_globals)
│  File "/home/ubuntu/anaconda3/envs/spike_sorting/lib/python3.7/site-packages/ecephys_spike_sorting/modules/kilosort_helper/__main__.py", line 285, in <mod
│ule>
│    main()
│  File "/home/ubuntu/anaconda3/envs/spike_sorting/lib/python3.7/site-packages/ecephys_spike_sorting/modules/kilosort_helper/__main__.py", line 275, in main
│    output = run_kilosort(mod.args)
│  File "/home/ubuntu/anaconda3/envs/spike_sorting/lib/python3.7/site-packages/ecephys_spike_sorting/modules/kilosort_helper/__main__.py", line 130, in run_
│kilosort
│    nargout=0)
│  File "/home/ubuntu/anaconda3/envs/spike_sorting/lib/python3.7/site-packages/matlab/engine/matlabengine.py", line 71, in __call__
│    _stderr, feval=True).result()
│  File "/home/ubuntu/anaconda3/envs/spike_sorting/lib/python3.7/site-packages/matlab/engine/futureresult.py", line 67, in result
│    return self.__future.result(timeout)
│  File "/home/ubuntu/anaconda3/envs/spike_sorting/lib/python3.7/site-packages/matlab/engine/fevalfuture.py", line 82, in result
│    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
│matlab.engine.MatlabExecutionError:
│  File /home/ubuntu/neuropixel/Kilosort-3.0/preProcess/standalone_detector.m, line 63, in standalone_detector
│
│  File /home/ubuntu/neuropixel/Kilosort-3.0/preProcess/datashift2.m, line 58, in datashift2
│
│  File /home/ubuntu/neuropixel/data_for_ecephys/kilosort_datatemp/main_kilosort_multiversion.m, line 95, in main_kilosort_multiversion
│Undefined function 'spikedetector3' for input arguments of type 'gpuArray'.
│
│Error using subprocess>check_call (line 363)
│Python Error: CalledProcessError: Command '['/home/ubuntu/anaconda3/envs/spike_sorting/bin/python', '-W', 'ignore', '-m',
│'ecephys_spike_sorting.modules.kilosort_helper', '--input_json', '/home/ubuntu/neuropixel/neuropixels-toolkit/configs/SC011_021919_imec0-input.json',
│'--output_json', '/home/ubuntu/neuropixel/neuropixels-toolkit/configs/SC011_021919_imec0-kilosort_helper-output.json']' returned non-zero exit status 1.
│
│Error in run_one_probe>runOne (line 36)
```

---

Hi there,

Hope everything is going well!
I'm having this issue right now while I was running Kilosort3.0, still don't have any clue. Please let me know if you guys need more info to help. I'll try to switch back to Kilosort2.5 and bring the update later, thanks!

---

Update: Kilosort 2.5 has the same issue.

**Comment by Yambottle** [comment]
Figured out by myself. It turns out I didn't run `mexGPUall.m`.
Also, for Linux user:
- when you install NVIDIA driver or CUDA toolkit, use `.run` option instead of `.deb`. 
- DON'T use `sudo apt install nvidia-cuda-tookit`
- downgrade gcc to 8.*

**Comment by luiztauffer** [comment]
I encountered the same problem and simply had to run `mexGPUall.m`. 
As opposed to @yambottle , my gcc is `9.4.0` and I used `sudo apt install nvidia-cuda-tookit`, and Kilosort3 worked well
