### ISSUE TITLE
INSTALLATION: Kilosort expects a module named `torch`

### ISSUE THREAD

**Issue by tiburona** [MouseLand/Kilosort#602]
### Describe the issue:

As instructed, I executed `pip uninstall torch` with my conda environment activated, and afterwords installed `pytorch` using the line in the instructions.  When I run `python -m kilosort` I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\Katie\anaconda3\envs\kilosort\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Katie\anaconda3\envs\kilosort\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\Katie\anaconda3\envs\kilosort\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Katie\software\Kilosort-main\kilosort\__init__.py", line 4, in <module>
    from .run_kilosort import run_kilosort
  File "C:\Users\Katie\software\Kilosort-main\kilosort\run_kilosort.py", line 5, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

### Provide environment info:

Here's the output of `conda info` in my Kilosort environment:

```
     active environment : kilosort
    active env location : C:\Users\Katie\anaconda3\envs\kilosort
            shell level : 2
       user config file : C:\Users\Katie\.condarc
 populated config files : C:\Users\Katie\.condarc
          conda version : 24.1.2
    conda-build version : 24.1.2
         python version : 3.11.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64
                          __conda=24.1.2=0
                          __cuda=11.6=0
                          __win=0=0
       base environment : C:\Users\Katie\anaconda3  (writable)
      conda av data dir : C:\Users\Katie\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Katie\anaconda3\pkgs
                          C:\Users\Katie\.conda\pkgs
                          C:\Users\Katie\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Katie\anaconda3\envs
                          C:\Users\Katie\.conda\envs
                          C:\Users\Katie\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/24.1.2 requests/2.31.0 CPython/3.11.7 Windows/10 Windows/10.0.22000 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.6 aau/0.4.3 c/S5VitPH_CV5SaV64HDyucA s/YTB_EADsYCB4EznzFfhHyw e/Ra4gh3tJMAdrRnVX6LGZcA
          administrator : False
             netrc file : None
           offline mode : False
```
I am, truth be told, a little confused by this output/not sure that it's what you're looking for.  Particularly the python-version is not what I have in my Kilosort environment.  Here's the result of python --version in the same environment: Python 3.9.18

### Operating system information:

Windows 11 Pro version 21H2

**Comment by jacobpennington** [comment]
Can you try running `conda list torch` with your Kilosort environment? If the GPU version of pytorch was installed, you should see something like this:
```
(kilosort4) PS C:\code\Kilosort> conda list torch
# packages in environment at C:\ProgramData\anaconda3\envs\kilosort4:       
#
# Name                    Version                   Build  Channel
pytorch                   2.2.1           py3.9_cuda11.8_cudnn8_0    pytorch
pytorch-cuda              11.8                 h24eeafa_5    pytorch        
pytorch-mutex             1.0                        cuda    pytorch     
```

**Comment by tiburona** [comment]
Hey, I realized that pytorch installation had failed, and fixed it myself.  Sorry to take your attention!  All is well now and the gui has started.
