### ISSUE TITLE
Issues Getting Kilosort To Run

### ISSUE THREAD

**Issue by MaLab24** [MouseLand/Kilosort#614]
### Describe the issue:

Hello, 

I recently installed Kilosort and I originally was running into this issue:

**QObject::moveToThread: Current thread (0x2a7734988a0) is not the object's thread (0x2a77349d4e0).
Cannot move to target thread (0x2a7734988a0)
qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "C:\Users\lanzi\anaconda3\envs\kilosort\Lib\site-packages\PyQt5" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.**

I believe that I was able to resolve this issue by doing this:

**conda remove qt
conda remove pyqt 
conda install qt 
conda install pyqt**

It seems that it fixed the error I was getting before, however, now when I try to run python -m kilosort, I get this error:

**Traceback (most recent call last):
  File "C:\Users\malab\.conda\envs\kilosort\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\malab\.conda\envs\kilosort\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\malab\.conda\envs\kilosort\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\malab\Documents\Kilosort\Kilosort\kilosort\__init__.py", line 3, in <module>
    from .utils import PROBE_DIR, DOWNLOADS_DIR
  File "C:\Users\malab\Documents\Kilosort\Kilosort\kilosort\utils.py", line 2, in <module>
    from tqdm import tqdm
  File "C:\Users\malab\.conda\envs\kilosort\lib\site-packages\tqdm\__init__.py", line 3, in <module>
    from .cli import main  # TODO: remove in v5.0.0
  File "C:\Users\malab\.conda\envs\kilosort\lib\site-packages\tqdm\cli.py", line 9, in <module>
    from .std import TqdmKeyError, TqdmTypeError, tqdm
  File "C:\Users\malab\.conda\envs\kilosort\lib\site-packages\tqdm\std.py", line 20, in <module>
    from .utils import (
  File "C:\Users\malab\.conda\envs\kilosort\lib\site-packages\tqdm\utils.py", line 29, in <module>
    colorama.init(strip=False)
AttributeError: module 'colorama' has no attribute 'init'**

I'm not completely sure what the error is as I've installed all the files from the GitHub and I haven't messed with any of the python files. I was wondering if y'all may have an idea.

Thanks

**Comment by MaLab24** [comment]
If it may help, here's all the currently installed packages:

**Package                  Version
------------------------ -----------
cachetools               5.3.3
certifi                  2024.2.2
charset-normalizer       3.3.2
click                    8.1.7
cloudpickle              3.0.0
colorcet                 3.1.0
contourpy                1.2.0
cycler                   0.12.1
Cython                   3.0.8
dask                     2024.2.1
faiss-cpu                1.8.0
filelock                 3.13.1
fonttools                4.49.0
fsspec                   2024.2.0
ghp-import               2.1.0
gmpy2                    2.1.2
google-api-core          2.17.1
google-auth              2.28.1
google-cloud-core        2.4.1
google-cloud-storage     2.14.0
google-crc32c            1.5.0
google-resumable-media   2.7.0
googleapis-common-protos 1.62.0
h5py                     3.10.0
idna                     3.6
importlib_resources      6.1.2
iniconfig                2.0.0
Jinja2                   3.1.3
joblib                   1.3.2
kilosort                 0.1
kiwisolver               1.4.5
llvmlite                 0.42.0
locket                   1.0.0
Markdown                 3.5.2
MarkupSafe               2.1.3
matplotlib               3.8.3
mergedeep                1.3.4
mkdocs                   1.5.3
mpmath                   1.3.0
mtscomp                  1.0.2
networkx                 3.1
numba                    0.59.0
numpy                    1.23.0
packaging                23.1
partd                    1.4.1
pathspec                 0.12.1
phy                      2.0b5
phylib                   2.4.3
pillow                   10.2.0
pip                      23.3.1
pluggy                   1.4.0
ply                      3.11
protobuf                 4.25.3
pyasn1                   0.5.1
pyasn1-modules           0.3.0
PyOpenGL                 3.1.7
pyparsing                3.1.1
PyQt5                    5.15.10
PyQt5-Qt5                5.15.2
PyQt5-sip                12.13.0
pyqtgraph                0.12.0
PyQtWebEngine            5.15.6
PyQtWebEngine-Qt5        5.15.2
pytest                   8.0.2
PyYAML                   6.0.1
pyyaml_env_tag           0.1
rsa                      4.9
scikit-learn             1.4.1.post1
scipy                    1.12.0
setuptools               68.2.2
sip                      6.7.12
sympy                    1.12
threadpoolctl            3.3.0
tomli                    2.0.1
toolz                    0.12.1
torch                    2.2.1
tqdm                     4.66.2
typing_extensions        4.10.0
urllib3                  2.2.1
watchdog                 4.0.0
wheel                    0.41.2**
