### ISSUE TITLE
Running kilosort4: Error 403 "Forbidden" 

### ISSUE THREAD

**Issue by AnnaB27** [MouseLand/Kilosort#615]
### Describe the issue:

Hi,
I successfully installed and run kilosort4 on my computer without any problems, using the dataset provided by you as example. I want now to try running my own data, However these data are found on a computer that I access remotly by VPN connection. I followed the same steps and I installed kilosort but once I run "python -m kilosort" to open the guide, it gives me the error 403 showed below. I guess it refers to some authorization issues and/or could be related to my remote connection to the pc where I want to run kilosort? Is there a way to fix the problem?
Thank you
Traceback (most recent call last):
  File "C:\Users\Anna B\anaconda3\envs\kilosort\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Anna B\anaconda3\envs\kilosort\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Anna B\anaconda3\envs\kilosort\lib\site-packages\kilosort\__main__.py", line 10, in <module>
    launcher(args.filename)
  File "C:\Users\Anna B\anaconda3\envs\kilosort\lib\site-packages\kilosort\gui\launch.py", line 28, in launcher
    kilosort_gui = KiloSortGUI(kilosort_application, filename=filename)
  File "C:\Users\Anna B\anaconda3\envs\kilosort\lib\site-packages\kilosort\gui\main.py", line 78, in __init__
    download_probes(self.new_probe_files_path)
  File "C:\Users\Anna B\anaconda3\envs\kilosort\lib\site-packages\kilosort\utils.py", line 42, in download_probes
    download_url_to_file(url, cached_file, progress=True)
  File "C:\Users\Anna B\anaconda3\envs\kilosort\lib\site-packages\kilosort\utils.py", line 57, in download_url_to_file
    u = urlopen(url)
  File "C:\Users\Anna B\anaconda3\envs\kilosort\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Anna B\anaconda3\envs\kilosort\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\Anna B\anaconda3\envs\kilosort\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\Anna B\anaconda3\envs\kilosort\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\Anna B\anaconda3\envs\kilosort\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\Anna B\anaconda3\envs\kilosort\lib\urllib\request.py", line 641, in http_error_default
    ****raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
``` 

### Provide environment info:

conda 22.9
python 3.9

### Operating system information:

windows server 2019

**Comment by AnnaB27** [comment]
Yes, indeed i am accessing an university network that's why I thought that could be the issue. Thank you very much anyway, I will try again re-installing from source. For the probes, I have my own .mat configuration file and I already put it in the right directory. Thank very much
I will let you know if it works.

**Comment by AnnaB27** [comment]
I re-installed from source as you suggested and now I maneged to open the guide.
Thank you again

**Comment by jacobpennington** [comment]
Great!

**Comment by robinhaak** [comment]
Hi, 

I experience a similar problem when running _python -m kilosort_:

(kilosort) C:\windows\system32>python -m kilosort
downloading logo
Traceback (most recent call last):
  File "C:\Users\haak\AppData\Local\anaconda3\envs\kilosort\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\haak\AppData\Local\anaconda3\envs\kilosort\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\windows\system32\kilosort\kilosort\__main__.py", line 10, in <module>
    launcher(args.filename)
  File "c:\windows\system32\kilosort\kilosort\gui\launch.py", line 31, in launcher
    download_url_to_file(
  File "c:\windows\system32\kilosort\kilosort\utils.py", line 62, in download_url_to_file
    u = urlopen(url)
  File "C:\Users\haak\AppData\Local\anaconda3\envs\kilosort\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\haak\AppData\Local\anaconda3\envs\kilosort\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\haak\AppData\Local\anaconda3\envs\kilosort\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\haak\AppData\Local\anaconda3\envs\kilosort\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\haak\AppData\Local\anaconda3\envs\kilosort\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\haak\AppData\Local\anaconda3\envs\kilosort\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

Is there a way to fix this?

**Comment by jacobpennington** [comment]
@robinhaak  Thanks for catching that, I've pushed a fix. You will have to pull the latest changes and then install from source again.

**Comment by robinhaak** [comment]
@jacobpennington Thanks for the quick reply and fix! I can use the GUI now
