### ISSUE TITLE
BUG: phy gives IndexError and phy can run when the same data is sorted in Kilosort 2.0

### ISSUE THREAD

**Issue by tiburona** [MouseLand/Kilosort#616]
### Describe the issue:

Kilosort 4 successfully runs on my data but when I try to view the data in phy I get an index error. I can open phy on the params file for the same data processed in Kilosort 2.0.

### Reproduce the bug:

Here is how I invoke Kilosort

```python



animals = ['160', '163', '176', '178', '180', '154', '156', '158', '175', '177', '179']

probe_dictionary = {
    'chanMap': np.array([1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]),
    'xc': np.array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]),
    'kcoords': np.zeros(14),
    'n_chan': 16,
    'yc': [90, 100, 30, 110, 40, 120, 50, 130, 60, 140, 70, 150, 80, 160]
}

save_probe(probe_dictionary, os.path.join(root_dir, 'probe.json'))
probe = load_probe(os.path.join(root_dir, 'probe.json'))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


settings = {'n_chan_bin': 16, 'data_dtype': 'float64', 'device': device}

for animal in animals:
    data_binary = root_dir / f'IG{animal}' / 'data_binary.bin'  # Corrected path representation
    settings['data_dir'] = data_binary.parent
    ops, st, clu, tF, Wall, similar_templates, is_ref, est_contam_rate = run_kilosort(settings=settings, probe=probe)
```

(I'm not sure if this, like my last issue, could be about units.  It might be worth saying that our recording setup is somewhat of an uneasy fit for KS because we don't have a rigid shank and I'm in the process of discussing with my PI the best values for ycoords, but in the meantime I'm also trying to see if I can get KS4 to work.)
```


### Error message:

```shell
21:36:11.054 [E] __init__:62          An error has occurred (IndexError): index 26 is out of bounds for axis 0 with size 26 Traceback (most recent call last): File "C:\Users\Katie\anaconda3\envs\phy2\lib\runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Users\Katie\anaconda3\envs\phy2\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\Users\Katie\anaconda3\envs\phy2\Scripts\phy.exe\__main__.py", line 7, in <module> sys.exit(phycli()) File "C:\Users\Katie\anaconda3\envs\phy2\lib\site-packages\click\core.py", line 1157, in __call__ return self.main(*args, **kwargs) File "C:\Users\Katie\anaconda3\envs\phy2\lib\site-packages\click\core.py", line 1078, in main rv = self.invoke(ctx) File "C:\Users\Katie\anaconda3\envs\phy2\lib\site-packages\click\core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "C:\Users\Katie\anaconda3\envs\phy2\lib\site-packages\click\core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) File "C:\Users\Katie\anaconda3\envs\phy2\lib\site-packages\click\core.py", line 783, in invoke return __callback(*args, **kwargs) File "C:\Users\Katie\anaconda3\envs\phy2\lib\site-packages\click\decorators.py", line 33, in new_func return f(get_current_context(), *args, **kwargs) File "C:\Users\Katie\anaconda3\envs\phy2\lib\site-packages\phy\apps\__init__.py", line 159, in cli_template_gui template_gui(params_path, **kwargs) File "C:\Users\Katie\anaconda3\envs\phy2\lib\site-packages\phy\apps\template\gui.py", line 209, in template_gui model = load_model(params_path) File "C:\Users\Katie\anaconda3\envs\phy2\lib\site-packages\phylib\io\model.py", line 1433, in load_model return TemplateModel(**get_template_params(params_path)) File "C:\Users\Katie\anaconda3\envs\phy2\lib\site-packages\phylib\io\model.py", line 339, in __init__ self._load_data() File "C:\Users\Katie\anaconda3\envs\phy2\lib\site-packages\phylib\io\model.py", line 419, in _load_data self.sparse_clusters = self.cluster_waveforms() File "C:\Users\Katie\anaconda3\envs\phy2\lib\site-packages\phylib\io\model.py", line 1319, in cluster_waveforms mean_waveform = self.get_cluster_mean_waveforms(clust, unwhiten=False) File "C:\Users\Katie\anaconda3\envs\phy2\lib\site-packages\phylib\io\model.py", line 1215, in get_cluster_mean_waveforms template = self.get_template(best_template, unwhiten=unwhiten) File "C:\Users\Katie\anaconda3\envs\phy2\lib\site-packages\phylib\io\model.py", line 959, in get_template return self._get_template_dense( File "C:\Users\Katie\anaconda3\envs\phy2\lib\site-packages\phylib\io\model.py", line 881, in _get_template_dense template_w = self.sparse_templates.data[template_id, ...] File "C:\Users\Katie\anaconda3\envs\phy2\lib\site-packages\numpy\core\memmap.py", line 334, in __getitem__ res = super().__getitem__(index) IndexError: index 26 is out of bounds for axis 0 with size 26
```

### Version information:

Python 3.9.18
Windows 11 Pro 21H2
CUDA11.6

**Comment by jacobpennington** [comment]
Hello, a couple things to check:

First, can you try reinstalling (either from pypi or from source), unless you've reinstalled in the last few days? This is a slightly different error, but looks like it could be related to #601 which was fixed after the initial release.

If that doesn't help, would you be able to paste in the text output Kilosort gives when sorting? Or if you're able to share a sample of data for me to debug it myself, that would work too.

**Comment by jacobpennington** [comment]
I'm going to close this for now, if you still have issues after reinstalling please let us know.
