### ISSUE TITLE
Questions about the probe creation tool

### ISSUE THREAD

**Issue by 18702505250** [MouseLand/Kilosort#658]
### Describe the issue:

When I click select probe layout on the kilosort4 interface and select new, no probe creation tool is displayed. The message log box prompts as follows: Traceback (most recent call last):

File "E:\Users\admin\anaconda3\envs\kilosort\lib\site-packages\kilosort\gui\settings_box.py", line 530,  in on_probe_layout_selected

dialog = ProbeBuilder(parent=self)

File "E:\Users\admin\anaconda3\envs\kilosort\lib\site-packages\kilosort\gui\minor_gui_elements.py", line 88, in __init__

self.setup()

File "E:\Users\admin\anaconda3\envs\kilosort\lib\site-packages\kilosort\gui\minor_gui_elements.py", line 116, in setup

error_label_palette.setColor(QtGui.QPalette.Foreground, QtGui.QColor("red"))

AttributeError
:
type object 'QPalette' has no attribute 'Foreground'
How should I handle this?

**Comment by jacobpennington** [comment]
@18702505250 Please take a look at the solutions in #669, this appears to be the same problem. Please let us know if that doesn't work.

**Comment by 18702505250** [comment]
Thank you very much for your meaningful suggestions. Reinstallation helped me solve this problem!
