### ISSUE TITLE
After converting the Intan data, the loaded data is empty.

### ISSUE THREAD

**Issue by Fusenheizi** [MouseLand/Kilosort#718]
### Describe the issue:

I used Kilosort to convert Intan .rhs data to .bin format. The conversion parameters are shown in the figure, and I used stream_id '0', which represents the channel signal data stream of Intan in spikeinterface (https://github.com/SpikeInterface/spikeinterface/issues/3018#issuecomment-2162846197). 
![image](https://github.com/MouseLand/Kilosort/assets/78153753/86bc2981-25a5-4829-aa79-2ce7b9273c2c)

Since the Intan data I used contains signals from 128 channels, I generated a probe for 128 channels using this code. 
```
import numpy as np
from kilosort.io import save_probe

chanMap = np.arange(128)
kcoords = np.zeros(128)
n_chan = 128

xc = np.ones(128)*5.5
yc = np.array([7.5 + 20*i for i in range(128)])

probe = {
    'chanMap': chanMap,
    'xc': xc,
    'yc': yc,
    'kcoords': kcoords,
    'n_chan': n_chan
}

print(probe)

save_probe(probe, 'probe128.json')
```
Everything seemed to meet the requirements. However, when I tried to click 'run' to execute, Kilosort returned an error indicating that the data is empty. I am not sure what went wrong or how to resolve this issue.
![image](https://github.com/MouseLand/Kilosort/assets/78153753/8bfce1d4-6f51-49bc-9fd6-fb7fd26ac6f8)
```
kilosort.run_kilosort:  

kilosort.run_kilosort: Computing preprocessing variables.

kilosort.run_kilosort: ----------------------------------------

kilosort.run_kilosort: Preprocessing filters computed in  0.08s; total  0.08s

kilosort.run_kilosort:  

kilosort.run_kilosort: Computing drift correction.

kilosort.run_kilosort: ----------------------------------------

kilosort.spikedetect: Re-computing universal templates from data.

Traceback (most recent call last):

  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\kilosort\gui\sorter.py", line 72, in run
    
ops, bfile, st0 = compute_drift_correction(

  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\kilosort\run_kilosort.py", line 394, in compute_drift_correction
    
ops, st = datashift.run(ops, bfile, device=device, progress_bar=progress_bar)

  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\kilosort\datashift.py", line 197, in run
    
st, _, ops  = spikedetect.run(ops, bfile, device=device, progress_bar=progress_bar)

  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 189, in run

    
ops['wPCA'], ops['wTEMP'] = extract_wPCA_wTEMP(

  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 72, in extract_wPCA_wTEMP
    
model = TruncatedSVD(n_components=ops['settings']['n_pcs']).fit(clips)

  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\decomposition\_truncated_svd.py", line 208, in fit
    
self.fit_transform(X)

  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\utils\_set_output.py", line 313, in wrapped
    
data_to_wrap = f(self, X, *args, **kwargs)

  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\base.py", line 1473, in wrapper
    
return fit_method(estimator, *args, **kwargs)

  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\decomposition\_truncated_svd.py", line 228, in fit_transform
    
X = self._validate_data(X, accept_sparse=["csr", "csc"], ensure_min_features=2)

  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\base.py", line 633, in _validate_data
 
out = check_array(X, input_name="X", **check_params)

  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\utils\validation.py", line 1082, in check_array
 
raise ValueError(

ValueError
: 
Found array with 0 sample(s) (shape=(0, 61)) while a minimum of 1 is required by TruncatedSVD.
```

Here, I have attached the Intan .rhs data I used, the generated probe, and the converted .bin data.
Datalink: https://wormhole.app/Wek9P#pf3IN8Un4xZelsmmyvUCAQ

**Comment by jacobpennington** [comment]
The data is in uint16 format, not int16. I was able to load it as uint16 and sort it without any issues. Did you actually select 'int16' when you converted the data, or did you select 'uint16' and then forget to change it for the screenshot?

**Comment by Fusenheizi** [comment]
> The data is in uint16 format, not int16. I was able to load it as uint16 and sort it without any issues. Did you actually select 'int16' when you converted the data, or did you select 'uint16' and then forget to change it for the screenshot?数据采用 uint16 格式，而不是 int16。我能够将其加载为 uint16 并对其进行排序而不会出现任何问题。您在转换数据时是否真的选择了“int16”，或者您选择了“uint16”，然后忘记为屏幕截图更改它？

Oh! Thank you for your reminder😣. I indeed mistakenly used 'int16' because I didn't understand the note in the converter GUI initially. After switching to 'uint16', the data could be loaded, as shown in the image. However, an error still occurs after clicking 'run':
![image](https://github.com/MouseLand/Kilosort/assets/78153753/04e840d6-a475-4b39-a17c-e86c271ddbdb)
```
kilosort.run_kilosort:  

kilosort.run_kilosort: Computing preprocessing variables.

kilosort.run_kilosort: ----------------------------------------

kilosort.run_kilosort: Preprocessing filters computed in  0.09s; total  0.09s

kilosort.run_kilosort:  

kilosort.run_kilosort: Computing drift correction.

kilosort.run_kilosort: ----------------------------------------

kilosort.spikedetect: Re-computing universal templates from data.

Traceback (most recent call last):

  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\kilosort\gui\sorter.py", line 72, in run

    
ops, bfile, st0 = compute_drift_correction(


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\kilosort\run_kilosort.py", line 394, in compute_drift_correction

    
ops, st = datashift.run(ops, bfile, device=device, progress_bar=progress_bar)


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\kilosort\datashift.py", line 197, in run

    
st, _, ops  = spikedetect.run(ops, bfile, device=device, progress_bar=progress_bar)


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 189, in run

    
ops['wPCA'], ops['wTEMP'] = extract_wPCA_wTEMP(


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 72, in extract_wPCA_wTEMP

    
model = TruncatedSVD(n_components=ops['settings']['n_pcs']).fit(clips)


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\decomposition\_truncated_svd.py", line 208, in fit

    
self.fit_transform(X)


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\utils\_set_output.py", line 313, in wrapped

    
data_to_wrap = f(self, X, *args, **kwargs)


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\base.py", line 1473, in wrapper

    
return fit_method(estimator, *args, **kwargs)


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\decomposition\_truncated_svd.py", line 228, in fit_transform

    
X = self._validate_data(X, accept_sparse=["csr", "csc"], ensure_min_features=2)


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\base.py", line 633, in _validate_data

    
out = check_array(X, input_name="X", **check_params)


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\utils\validation.py", line 1082, in check_array

    
raise ValueError(


ValueError
: 
Found array with 0 sample(s) (shape=(0, 61)) while a minimum of 1 is required by TruncatedSVD.
```

**Comment by jacobpennington** [comment]
Are you using the latest version of Kilosort4?

**Comment by Fusenheizi** [comment]
> Are you using the latest version of Kilosort4?

No, I use v4.0.11. But same thing happened in v4.0.12.
![image](https://github.com/MouseLand/Kilosort/assets/78153753/b7c78a97-8455-4656-97ca-7dc6e6007fd6)
```
INFO: The correct number of channels has been estimated to be 128.
kilosort.gui.sorter: Kilosort version 4.0.12

kilosort.gui.sorter: Sorting C:\ephys_cl\v2_4rats_test.bin

kilosort.gui.sorter: ----------------------------------------

kilosort.run_kilosort:  

kilosort.run_kilosort: Computing preprocessing variables.

kilosort.run_kilosort: ----------------------------------------

kilosort.run_kilosort: Preprocessing filters computed in  0.17s; total  0.17s

kilosort.run_kilosort:  

kilosort.run_kilosort: Computing drift correction.

kilosort.run_kilosort: ----------------------------------------

kilosort.spikedetect: Re-computing universal templates from data.

Traceback (most recent call last):

  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\kilosort\gui\sorter.py", line 93, in run

    
ops, bfile, st0 = compute_drift_correction(


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\kilosort\run_kilosort.py", line 425, in compute_drift_correction

    
ops, st = datashift.run(ops, bfile, device=device, progress_bar=progress_bar)


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\kilosort\datashift.py", line 197, in run

    
st, _, ops  = spikedetect.run(ops, bfile, device=device, progress_bar=progress_bar)


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 204, in run

    
ops['wPCA'], ops['wTEMP'] = extract_wPCA_wTEMP(


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 72, in extract_wPCA_wTEMP

    
model = TruncatedSVD(n_components=ops['settings']['n_pcs']).fit(clips)


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\decomposition\_truncated_svd.py", line 208, in fit

    
self.fit_transform(X)


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\utils\_set_output.py", line 313, in wrapped

    
data_to_wrap = f(self, X, *args, **kwargs)


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\base.py", line 1473, in wrapper

    
return fit_method(estimator, *args, **kwargs)


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\decomposition\_truncated_svd.py", line 228, in fit_transform

    
X = self._validate_data(X, accept_sparse=["csr", "csc"], ensure_min_features=2)


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\base.py", line 633, in _validate_data

    
out = check_array(X, input_name="X", **check_params)


  File "C:\Users\319_exp\.conda\envs\kilosort\lib\site-packages\sklearn\utils\validation.py", line 1082, in check_array

    
raise ValueError(


ValueError
: 
Found array with 0 sample(s) (shape=(0, 61)) while a minimum of 1 is required by TruncatedSVD.
```
And Kilosort doesn't detect my GPU after I followed the steps to reinstall v4.0.12🥲.

**Comment by Fusenheizi** [comment]
I don't know what happened, but after clicking 'Clear Cache' and 'Reset GUI', everything goes well😌. Thank You!

![image](https://github.com/MouseLand/Kilosort/assets/78153753/ee666c74-cb11-4835-a975-09be0af71f2d)
