### ISSUE TITLE
Kilosort4 runs into Zero Division Error - float division by zero 

### ISSUE THREAD

**Issue by Sfrap99** [MouseLand/Kilosort#724]
### Describe the issue:

I had been running Kilosort4 through the GUI on quite a few of my recordings without incurring into any issues, but on the recent files I am spike sorting I get an annoying error at the final clustering stage - a 'ZeroDivisionError' as highlighted below. When I run kilosort on previous files it still appears to work.  
[kilosort4.log](https://github.com/user-attachments/files/15903815/kilosort4.log)

### Reproduce the bug:

```python
Just the GUI - I loaded the continous.dat and the probe map for this file.
```

### Error message:

```shell
WARNING: The results directory Z:\Francesca\compReplay_mEC\experiment\raw_data\ephys\MR1_NM\2024-06-18_09-08-36\Record Node 101\experiment1\recording1\continuous\Neuropix-PXI-100.ProbeA\kilosort4 does not exist.
WARNING: It will be (recursively) created upon data load.
INFO: The correct number of channels has been estimated to be 384.
kilosort.gui.sorter: Kilosort version 4.0.12

kilosort.gui.sorter: Sorting Z:\Francesca\compReplay_mEC\experiment\raw_data\ephys\MR1_NM\2024-06-18_09-08-36\Record Node 101\experiment1\recording1\continuous\Neuropix-PXI-100.ProbeA\continuous.dat

kilosort.gui.sorter: ----------------------------------------

kilosort.run_kilosort:  

kilosort.run_kilosort: Computing preprocessing variables.

kilosort.run_kilosort: ----------------------------------------

kilosort.run_kilosort: Preprocessing filters computed in  2.12s; total  2.13s

kilosort.run_kilosort:  

kilosort.run_kilosort: Computing drift correction.

kilosort.run_kilosort: ----------------------------------------

kilosort.spikedetect: Re-computing universal templates from data.


  0%|                                                                                          | 0/923 [00:00<?, ?it/s]

  0%|                                                                                          | 0/923 [00:20<?, ?it/s]

  5%|####3                                                                            | 50/923 [01:01<17:45,  1.22s/it]

 11%|########6                                                                        | 99/923 [02:01<16:56,  1.23s/it]

 16%|############8                                                                   | 148/923 [03:02<15:55,  1.23s/it]

 21%|#################                                                               | 197/923 [04:02<14:56,  1.23s/it]

 27%|#####################4                                                          | 247/923 [05:03<13:50,  1.23s/it]

 32%|#########################6                                                      | 296/923 [06:04<12:50,  1.23s/it]

 36%|############################9                                                   | 334/923 [07:04<13:03,  1.33s/it]

 41%|################################9                                               | 380/923 [08:05<11:59,  1.32s/it]

 46%|#####################################1                                          | 429/923 [09:06<10:42,  1.30s/it]

 52%|#########################################4                                      | 478/923 [10:07<09:29,  1.28s/it]

 57%|#############################################5                                  | 525/923 [11:07<08:30,  1.28s/it]

 62%|#################################################7                              | 574/923 [12:08<07:23,  1.27s/it]

 67%|#####################################################9                          | 623/923 [13:09<06:18,  1.26s/it]

 73%|##########################################################2                     | 672/923 [14:09<05:13,  1.25s/it]

 78%|##############################################################4                 | 721/923 [15:09<04:11,  1.24s/it]

 83%|##################################################################7             | 770/923 [16:11<03:10,  1.25s/it]

 89%|######################################################################8         | 817/923 [17:11<02:13,  1.26s/it]

 94%|###########################################################################     | 866/923 [18:12<01:11,  1.25s/it]

 99%|###############################################################################2| 914/923 [19:13<00:11,  1.26s/it]


100%|################################################################################| 923/923 [19:24<00:00,  1.26s/it]


kilosort.run_kilosort: drift computed in  1175.11s; total  1177.25s

kilosort.run_kilosort:  

kilosort.run_kilosort: Extracting spikes using templates

kilosort.run_kilosort: ----------------------------------------

kilosort.spikedetect: Re-computing universal templates from data.


  0%|                                                                                          | 0/923 [00:00<?, ?it/s]

  0%|                                                                                          | 0/923 [00:16<?, ?it/s]

  5%|####3                                                                            | 49/923 [01:00<17:59,  1.23s/it]

 11%|########6                                                                        | 99/923 [02:01<16:48,  1.22s/it]

 16%|############5                                                                   | 145/923 [03:02<16:27,  1.27s/it]

 21%|################6                                                               | 192/923 [04:02<15:30,  1.27s/it]

 26%|####################9                                                           | 242/923 [05:03<14:14,  1.26s/it]

 32%|#########################3                                                      | 292/923 [06:04<13:04,  1.24s/it]

 37%|#############################5                                                  | 341/923 [07:05<12:03,  1.24s/it]

 42%|#################################8                                              | 391/923 [08:05<10:54,  1.23s/it]

 48%|######################################                                          | 439/923 [09:05<09:58,  1.24s/it]

 51%|#########################################                                       | 474/923 [10:06<10:08,  1.36s/it]

 57%|#############################################2                                  | 522/923 [11:06<08:50,  1.32s/it]

 61%|#################################################                               | 566/923 [12:06<07:57,  1.34s/it]

 66%|#####################################################                           | 612/923 [13:07<06:54,  1.33s/it]

 71%|#########################################################                       | 658/923 [14:08<05:52,  1.33s/it]

 76%|#############################################################                   | 704/923 [15:09<04:51,  1.33s/it]

 81%|################################################################9               | 749/923 [16:09<03:51,  1.33s/it]

 86%|####################################################################9           | 795/923 [17:09<02:49,  1.32s/it]

 91%|########################################################################8       | 841/923 [18:16<01:51,  1.36s/it]

 96%|############################################################################7   | 885/923 [19:19<00:52,  1.38s/it]


100%|################################################################################| 923/923 [20:11<00:00,  1.31s/it]


kilosort.run_kilosort: 3291290 spikes extracted in  1253.47s; total  2432.18s

kilosort.run_kilosort:  

kilosort.run_kilosort: First clustering

kilosort.run_kilosort: ----------------------------------------


  0%|                                                                                           | 0/72 [00:00<?, ?it/s]

  0%|                                                                                           | 0/72 [00:15<?, ?it/s]

  7%|#####7                                                                             | 5/72 [00:17<03:56,  3.53s/it]

 21%|#################                                                                 | 15/72 [00:27<01:35,  1.67s/it]

 36%|#############################6                                                    | 26/72 [00:38<00:59,  1.30s/it]

 47%|######################################7                                           | 34/72 [00:49<00:49,  1.30s/it]

 54%|############################################4                                     | 39/72 [00:59<00:49,  1.49s/it]

 67%|######################################################6                           | 48/72 [01:10<00:33,  1.38s/it]

 83%|####################################################################3             | 60/72 [01:22<00:14,  1.22s/it]


100%|##################################################################################| 72/72 [01:31<00:00,  1.27s/it]


kilosort.run_kilosort: 636 clusters found, in  92.61s; total  2524.86s

kilosort.run_kilosort:  

kilosort.run_kilosort: Extracting spikes using cluster waveforms

kilosort.run_kilosort: ----------------------------------------


  0%|                                                                                          | 0/923 [00:00<?, ?it/s]

  0%|                                                                                          | 0/923 [00:13<?, ?it/s]

  3%|##4                                                                              | 28/923 [01:01<32:35,  2.18s/it]

  6%|####7                                                                            | 54/923 [02:02<32:59,  2.28s/it]

  8%|######6                                                                          | 76/923 [03:04<35:23,  2.51s/it]

 10%|########3                                                                        | 95/923 [04:05<37:50,  2.74s/it]

 12%|#########7                                                                      | 112/923 [05:12<41:52,  3.10s/it]

 15%|###########7                                                                    | 136/923 [06:14<38:02,  2.90s/it]

 18%|##############                                                                  | 162/923 [07:14<34:07,  2.69s/it]

 20%|################1                                                               | 186/923 [08:16<32:35,  2.65s/it]

 23%|##################                                                              | 208/923 [09:19<32:17,  2.71s/it]

 25%|####################1                                                           | 232/923 [10:22<30:53,  2.68s/it]

 28%|######################2                                                         | 257/923 [11:25<29:11,  2.63s/it]

 31%|########################5                                                       | 283/923 [12:26<27:04,  2.54s/it]

 33%|##########################6                                                     | 308/923 [13:27<25:47,  2.52s/it]

 36%|############################6                                                   | 331/923 [14:28<25:13,  2.56s/it]

 39%|##############################9                                                 | 357/923 [15:30<23:35,  2.50s/it]

 41%|#################################1                                              | 383/923 [16:30<21:58,  2.44s/it]

 44%|###################################3                                            | 408/923 [17:31<20:54,  2.44s/it]

 47%|#####################################4                                          | 432/923 [18:31<20:08,  2.46s/it]

 50%|#######################################6                                        | 457/923 [19:33<19:07,  2.46s/it]

 52%|#########################################6                                      | 481/923 [20:34<18:17,  2.48s/it]

 54%|###########################################5                                    | 502/923 [21:34<18:07,  2.58s/it]

 57%|#############################################5                                  | 526/923 [22:35<17:00,  2.57s/it]

 59%|###############################################1                                | 544/923 [23:40<17:53,  2.83s/it]

 62%|#################################################7                              | 574/923 [24:42<14:48,  2.55s/it]

 66%|####################################################4                           | 605/923 [25:44<12:29,  2.36s/it]

 68%|######################################################6                         | 630/923 [26:47<11:42,  2.40s/it]

 71%|########################################################6                       | 654/923 [27:49<10:59,  2.45s/it]

 73%|##########################################################7                     | 678/923 [28:50<10:06,  2.47s/it]

 76%|############################################################7                   | 701/923 [29:50<09:18,  2.52s/it]

 78%|##############################################################7                 | 724/923 [30:50<08:26,  2.54s/it]

 81%|################################################################7               | 747/923 [31:52<07:34,  2.58s/it]

 83%|##################################################################6             | 769/923 [32:52<06:44,  2.63s/it]

 86%|####################################################################5           | 791/923 [33:53<05:53,  2.68s/it]

 88%|######################################################################1         | 809/923 [34:54<05:24,  2.85s/it]

 90%|########################################################################1       | 832/923 [35:55<04:13,  2.78s/it]

 93%|##########################################################################1     | 855/923 [36:58<03:09,  2.78s/it]

 95%|############################################################################    | 878/923 [37:59<02:03,  2.73s/it]

 98%|##############################################################################  | 901/923 [39:00<00:59,  2.71s/it]


100%|################################################################################| 923/923 [39:55<00:00,  2.60s/it]


kilosort.run_kilosort: 5760482 spikes extracted in  2397.17s; total  4922.08s

kilosort.run_kilosort:  

kilosort.run_kilosort: Final clustering

kilosort.run_kilosort: ----------------------------------------


  0%|                                                                                           | 0/72 [00:00<?, ?it/s]

  0%|                                                                                           | 0/72 [00:17<?, ?it/s]

  4%|###4                                                                               | 3/72 [00:18<06:55,  6.02s/it]

  7%|#####7                                                                             | 5/72 [00:32<07:20,  6.57s/it]

 19%|###############9                                                                  | 14/72 [00:42<02:23,  2.48s/it]

 32%|##########################1                                                       | 23/72 [00:53<01:28,  1.81s/it]

 46%|#####################################5                                            | 33/72 [01:06<01:01,  1.57s/it]

 51%|##########################################1                                       | 37/72 [01:17<01:04,  1.84s/it]

 64%|####################################################3                             | 46/72 [01:28<00:40,  1.56s/it]

 83%|####################################################################3             | 60/72 [01:40<00:14,  1.24s/it]


100%|##################################################################################| 72/72 [01:49<00:00,  1.52s/it]


kilosort.run_kilosort: 554 clusters found, in  109.28s; total  5031.45s

kilosort.run_kilosort:  

kilosort.run_kilosort: Merging clusters

kilosort.run_kilosort: ----------------------------------------

Traceback (most recent call last):

  File "C:\Users\Behre\miniconda3\envs\kilosort\lib\site-packages\kilosort\gui\sorter.py", line 120, in run

    
clu, Wall = cluster_spikes(st, tF, ops, self.device, bfile, tic0=tic0,


  File "C:\Users\Behre\miniconda3\envs\kilosort\lib\site-packages\kilosort\run_kilosort.py", line 534, in cluster_spikes

    
Wall, clu, is_ref = template_matching.merging_function(ops, Wall, clu, st[:,0],


  File "C:\Users\Behre\miniconda3\envs\kilosort\lib\site-packages\kilosort\template_matching.py", line 198, in merging_function

    
is_ref, est_contam_rate = CCG.refract(clu, st/ops['fs'],


  File "C:\Users\Behre\miniconda3\envs\kilosort\lib\site-packages\kilosort\CCG.py", line 108, in refract

    
is_refractory[kk], cross_refractory[kk], Q12[kk] = check_CCG(


  File "C:\Users\Behre\miniconda3\envs\kilosort\lib\site-packages\kilosort\CCG.py", line 81, in check_CCG

    
Q12, R12, R00 = CCG_metrics(st1, st2, K, T,  nbins = nbins, tbin = tbin)


  File "C:\Users\Behre\miniconda3\envs\kilosort\lib\site-packages\kilosort\CCG.py", line 44, in CCG_metrics

    
Q00 = K[irange1].sum() / (len(irange1) * tbin * len(st1) * len(st2) /T)


ZeroDivisionError
: 
float division by zero
```

### Version information:

Kilosort4 installed as per instructions on the git, Python 3.9.19

### Context for the issue:

I cannot spike sort some of my files

### Experiment information:

Neuropixels 2.0 (384 channels) in mEC

**Comment by jacobpennington** [comment]
Hello @Sfrap99,

Unfortunately I can't see any clear cause for this. Is it feasible for you to share the problematic data and probe file so that I can try sorting the data myself?

**Comment by Sfrap99** [comment]
Hello @jacobpennington and thanks for the reply. Yes, I can do that. Where can I share it?

**Comment by jacobpennington** [comment]
Uploading to google drive or a similar service and then sharing  a link here has been working well. You can also e-mail me the link at jacob.p.neuro@gmail.com if you don't want it to be publicly visible.

**Comment by atombysx** [comment]
Hi,

I'm encountering the same problem:

number of samples: 314004308
number of channels: 360
numbef of segments: 1
sampling rate: 29999.926666666666
dtype: int16
========================================
Preprocessing filters computed in  100.18s; total  100.18s
Skipping drift correction.

computing drift
nblocks = 0, skipping drift correction
drift computed in  0.00s; total  100.19s

Extracting spikes using templates
Re-computing universal templates from data.
  0%|          | 0/5234 [00:00<?, ?it/s]/home/miniconda3/lib/python3.11/site-packages/kilosort/spikedetect.py:118: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  B = conv1d(X.unsqueeze(1), W, padding=nt//2)
100%|██████████| 5234/5234 [2:24:23<00:00,  1.66s/it]  
19144525 spikes extracted in  8707.45s; total  8807.63s

First clustering
100%|██████████| 71/71 [49:26<00:00, 41.78s/it]   
/home/miniconda3/lib/python3.11/site-packages/kilosort/template_matching.py:71: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  X = conv1d(X.unsqueeze(1), ops['wTEMP'].unsqueeze(1), padding=ops['nt']//2)
744 clusters found, in  2968.96s; total  11776.59s

Extracting spikes using cluster waveforms
100%|██████████| 5234/5234 [1:03:24<00:00,  1.38it/s]
25548707 spikes extracted in  3811.30s; total  15587.89s

Final clustering
100%|██████████| 71/71 [54:56<00:00, 46.42s/it]   
570 clusters found, in  3296.13s; total  18884.02s

Merging clusters
Traceback (most recent call last):
  File "/home/lab/spikeinterface_sorting/temp_data/20240605/probe0/sorters/in_container_sorter_script.py", line 23, in <module>
    sorting = run_sorter_local(
              ^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/spikeinterface/sorters/runsorter.py", line 225, in run_sorter_local
    SorterClass.run_from_folder(output_folder, raise_error, verbose)
  File "/root/.local/lib/python3.11/site-packages/spikeinterface/sorters/basesorter.py", line 293, in run_from_folder
    raise SpikeSortingError(
spikeinterface.sorters.utils.misc.SpikeSortingError: Spike sorting error trace:
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/spikeinterface/sorters/basesorter.py", line 258, in run_from_folder
    SorterClass._run_from_folder(sorter_output_folder, sorter_params, verbose)
  File "/root/.local/lib/python3.11/site-packages/spikeinterface/sorters/external/kilosort4.py", line 244, in _run_from_folder
    clu, Wall = cluster_spikes(st, tF, ops, device, bfile, tic0=tic0, progress_bar=progress_bar)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/lib/python3.11/site-packages/kilosort/run_kilosort.py", line 433, in cluster_spikes
    Wall, clu, is_ref = template_matching.merging_function(ops, Wall, clu, st[:,0],
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/lib/python3.11/site-packages/kilosort/template_matching.py", line 191, in merging_function
    is_ref, est_contam_rate = CCG.refract(clu, st/ops['fs'],
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/lib/python3.11/site-packages/kilosort/CCG.py", line 108, in refract
    is_refractory[kk], cross_refractory[kk], Q12[kk] = check_CCG(
                                                       ^^^^^^^^^^
  File "/home/miniconda3/lib/python3.11/site-packages/kilosort/CCG.py", line 81, in check_CCG
    Q12, R12, R00 = CCG_metrics(st1, st2, K, T,  nbins = nbins, tbin = tbin)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/lib/python3.11/site-packages/kilosort/CCG.py", line 44, in CCG_metrics
    Q00 = K[irange1].sum() / (len(irange1) * tbin * len(st1) * len(st2) /T)
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
ZeroDivisionError: float division by zero

**Comment by Sfrap99** [comment]
I sent you the link by email - let me know and thank you very much!

**Comment by jacobpennington** [comment]
It's been fixed, thanks again for sharing the data. The change will be live with the next pypi update, which I'm hoping to have done in a day or two. You can also install from source and pull the latest changes if you want to try it now.

**Comment by Sfrap99** [comment]
That's great, thank you very much! I will let you know if I run into any other issues.

**Comment by dmitriivasilev** [comment]
Hi there, I've just encountered similar issue. You can check the HPC logs in the file attached:
[errKS-70762841.txt](https://github.com/user-attachments/files/16092398/errKS-70762841.txt)

**Comment by jacobpennington** [comment]
@dmitriivasilev Please upgrade to the latest version of Kilosort (v4.0.13) to get the fix for this.
