### ISSUE TITLE
BUG: CUDA out of memory error with no other software open

### ISSUE THREAD

**Issue by Lathomas42** [MouseLand/Kilosort#747]
### Describe the issue:

During First clustering, I get a CUDA out of memory error. Nothign else is open, computer has recently been restarted. I am on the head of the main branch and running via a jupyter notebook. I consistently get this for a relatively large recording (70 gb), 64 channels, 30khz, uint16.
Here is the kilosort4 log. Let me know if there's anything else I can do. I am using a 1080Ti.
[kilosort4.log](https://github.com/user-attachments/files/16401150/kilosort4.log)

### Error message:

```
Traceback (most recent call last):
  File "/auto/zdrive/lthomas/Code/Kilosort/kilosort/run_kilosort.py", line 181, in run_kilosort
    st,tF, _, _ = detect_spikes(ops, device, bfile, tic0=tic0,
  File "/auto/zdrive/lthomas/Code/Kilosort/kilosort/run_kilosort.py", line 542, in detect_spikes
    clu, Wall = clustering_qr.run(ops, st0, tF, mode='spikes', device=device,
  File "/auto/zdrive/lthomas/Code/Kilosort/kilosort/clustering_qr.py", line 364, in run
    iclust, iclust0, M, iclust_init = cluster(Xd, nskip=nskip, lam=1,
  File "/auto/zdrive/lthomas/Code/Kilosort/kilosort/clustering_qr.py", line 151, in cluster
    iclust = assign_iclust(rows_neigh, isub, kn, tones2, nclust, lam, m, ki, kj, device=device)
  File "/auto/zdrive/lthomas/Code/Kilosort/kilosort/clustering_qr.py", line 81, in assign_iclust
    xN = xN - lam/m * (ki.unsqueeze(-1) * kN.to_dense())
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.92 GiB. GPU 
```

```
  File "/auto/zdrive/lthomas/Code/Kilosort/kilosort/run_kilosort.py", line 181, in run_kilosort
    st,tF, _, _ = detect_spikes(ops, device, bfile, tic0=tic0,
  File "/auto/zdrive/lthomas/Code/Kilosort/kilosort/run_kilosort.py", line 542, in detect_spikes
    clu, Wall = clustering_qr.run(ops, st0, tF, mode='spikes', device=device,
  File "/auto/zdrive/lthomas/Code/Kilosort/kilosort/clustering_qr.py", line 364, in run
    iclust, iclust0, M, iclust_init = cluster(Xd, nskip=nskip, lam=1,
  File "/auto/zdrive/lthomas/Code/Kilosort/kilosort/clustering_qr.py", line 151, in cluster
    iclust = assign_iclust(rows_neigh, isub, kn, tones2, nclust, lam, m, ki, kj, device=device)
  File "/auto/zdrive/lthomas/Code/Kilosort/kilosort/clustering_qr.py", line 81, in assign_iclust
    xN = xN - lam/m * (ki.unsqueeze(-1) * kN.to_dense())
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.92 GiB. GPU 
```

### Version information:

Python 3.9.18
Kilosort latest commit b82e562
OS Ubuntu 20.04
GPU: 1080Ti
Nvidia Driver Version: 550.54.15 
CUDA Version: 12.4

**Comment by Lathomas42** [comment]
I see that maybe the CUDA version may be the issue, given other answers on this. Ill close this issue, as I think I saw some replicated issues. my bad.
