### ISSUE TITLE
RuntimeError and UnboundLocalError 

### ISSUE THREAD

**Issue by karmenrai2** [MouseLand/Kilosort#810]
### Describe the issue:

Using a dataset in Kilosort4, I keep getting a RuntimeError involving a shape error and a UnboundLocalError involving a local variable. 
![Screenshot 2024-10-31 160224](https://github.com/user-attachments/assets/2d18644a-80d9-4eec-90f6-879bf065f517)

### Error message:

```shell
kilosort.spikedetect: Error in spikedetect.run on batch 0
Traceback (most recent call last):
  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 263, in run
    xy, imax, amp, adist = template_match(X, ops, iC, iC2, weigh, device=device)
  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 157, in template_match
    A = A.reshape(-1, Nfilt, A.shape[-1])
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 1532, 0] because the unspecified dimension size -1 can be any value and is ambiguous

kilosort.gui.sorter: Encountered error in `run_kilosort`:
Traceback (most recent call last):
  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 263, in run
    xy, imax, amp, adist = template_match(X, ops, iC, iC2, weigh, device=device)
  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 157, in template_match
    A = A.reshape(-1, Nfilt, A.shape[-1])
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 1532, 0] because the unspecified dimension size -1 can be any value and is ambiguous

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\gui\sorter.py", line 95, in run
    ops, bfile, st0 = compute_drift_correction(
  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\run_kilosort.py", line 566, in compute_drift_correction
    ops, st = datashift.run(ops, bfile, device=device, progress_bar=progress_bar,
  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\datashift.py", line 198, in run
    st, _, ops  = spikedetect.run(
  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 289, in run
    logger.debug(f'xy shape: {xy.shape}')
UnboundLocalError: local variable 'xy' referenced before assignment

Traceback (most recent call last):

  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 263, in run

    
xy, imax, amp, adist = template_match(X, ops, iC, iC2, weigh, device=device)


  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 157, in template_match

    
A = A.reshape(-1, Nfilt, A.shape[-1])


RuntimeError
: 
cannot reshape tensor of 0 elements into shape [-1, 1532, 0] because the unspecified dimension size -1 can be any value and is ambiguous



During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\gui\sorter.py", line 95, in run

    
ops, bfile, st0 = compute_drift_correction(


  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\run_kilosort.py", line 566, in compute_drift_correction

    
ops, st = datashift.run(ops, bfile, device=device, progress_bar=progress_bar,


  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\datashift.py", line 198, in run

    
st, _, ops  = spikedetect.run(


  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 289, in run

    
logger.debug(f'xy shape: {xy.shape}')


UnboundLocalError
: 
local variable 'xy' referenced before assignment
```

### Version information:

 Kilosort version 4.0.20
![Screenshot 2024-10-31 160440](https://github.com/user-attachments/assets/fac748d4-b95c-4510-8070-0439e5f96d9f)
[kilosort4.log](https://github.com/user-attachments/files/17592830/kilosort4.log)

**Comment by jacobpennington** [comment]
Can you please try resetting `Th (universal)` and `Th (learned)` to their default values of 9 and 8, respectively?

**Comment by karmenrai2** [comment]
> Can you please try resetting `Th (universal)` and `Th (learned)` to their default values of 9 and 8, respectively?

I've tried that but I'm still getting the same results. I've attached the updated info below.

![Screenshot 2024-11-05 143654](https://github.com/user-attachments/assets/4ab5bfb5-ecc7-4bdf-a7ba-96783b7cf5a8)

kilosort.gui.sorter: Kilosort version 4.0.20

kilosort.gui.sorter: Sorting C:\Users\cognp\Documents\Kilosort4\continuous.dat

kilosort.gui.sorter: ----------------------------------------

kilosort.run_kilosort:  

kilosort.run_kilosort: Computing preprocessing variables.

kilosort.run_kilosort: ----------------------------------------

kilosort.run_kilosort: N samples: 40111071

kilosort.run_kilosort: N seconds: 1337.0357

kilosort.run_kilosort: N batches: 98553

kilosort.run_kilosort: Preprocessing filters computed in  2.48s; total  2.49s

kilosort.run_kilosort:  

kilosort.run_kilosort: Resource usage after preprocessing

kilosort.run_kilosort: ********************************************************

kilosort.run_kilosort: CPU usage:     0.00 %

kilosort.run_kilosort: Memory:       22.36 %     |     14.27   /    63.80 GB

kilosort.run_kilosort: ------------------------------------------------------

kilosort.run_kilosort: GPU usage:    `conda install pynvml` for GPU usage

kilosort.run_kilosort: GPU memory:   23.85 %     |      2.86   /    12.00 GB

kilosort.run_kilosort: Allocated:     0.31 %     |      0.04   /    12.00 GB

kilosort.run_kilosort: Max alloc:    11.10 %     |      1.33   /    12.00 GB

kilosort.run_kilosort: ********************************************************

kilosort.run_kilosort:  

kilosort.run_kilosort: Computing drift correction.

kilosort.run_kilosort: ----------------------------------------

kilosort.spikedetect: Re-computing universal templates from data.

kilosort.spikedetect: Number of universal templates: 1532

kilosort.spikedetect: Detecting spikes...


  0%|                                                                                        | 0/98553 [00:00<?, ?it/s]


  0%|                                                                                        | 0/98553 [00:00<?, ?it/s]


kilosort.spikedetect: Error in spikedetect.run on batch 0
Traceback (most recent call last):
  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 263, in run
    xy, imax, amp, adist = template_match(X, ops, iC, iC2, weigh, device=device)
  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 157, in template_match
    A = A.reshape(-1, Nfilt, A.shape[-1])
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 1532, 0] because the unspecified dimension size -1 can be any value and is ambiguous

kilosort.gui.sorter: Encountered error in `run_kilosort`:
Traceback (most recent call last):
  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 263, in run
    xy, imax, amp, adist = template_match(X, ops, iC, iC2, weigh, device=device)
  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 157, in template_match
    A = A.reshape(-1, Nfilt, A.shape[-1])
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 1532, 0] because the unspecified dimension size -1 can be any value and is ambiguous

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\gui\sorter.py", line 95, in run
    ops, bfile, st0 = compute_drift_correction(
  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\run_kilosort.py", line 566, in compute_drift_correction
    ops, st = datashift.run(ops, bfile, device=device, progress_bar=progress_bar,
  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\datashift.py", line 198, in run
    st, _, ops  = spikedetect.run(
  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 289, in run
    logger.debug(f'xy shape: {xy.shape}')
UnboundLocalError: local variable 'xy' referenced before assignment

Traceback (most recent call last):

  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 263, in run

    
xy, imax, amp, adist = template_match(X, ops, iC, iC2, weigh, device=device)


  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 157, in template_match

    
A = A.reshape(-1, Nfilt, A.shape[-1])


RuntimeError
: 
cannot reshape tensor of 0 elements into shape [-1, 1532, 0] because the unspecified dimension size -1 can be any value and is ambiguous



During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\gui\sorter.py", line 95, in run

    
ops, bfile, st0 = compute_drift_correction(


  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\run_kilosort.py", line 566, in compute_drift_correction

    
ops, st = datashift.run(ops, bfile, device=device, progress_bar=progress_bar,


  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\datashift.py", line 198, in run

    
st, _, ops  = spikedetect.run(


  File "C:\Users\cognp\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 289, in run

    
logger.debug(f'xy shape: {xy.shape}')


UnboundLocalError
: 
local variable 'xy' referenced before assignment

**Comment by jacobpennington** [comment]
Can you please attach `kilosort4.log` from the results directory so I can see all of the parameter values you used? A batch size of 407 is going to result in some strange behavior, and there may be other relevant settings as well.

**Comment by zetonew** [comment]
I also have the same issue:

logger.debug(f'xy shape: {xy.shape}')

UnboundLocalError
:
local variable 'xy' referenced before assignment

still do not figure out how to solve it.

**Comment by karmenrai2** [comment]
worked after changing the batch size

**Comment by jacobpennington** [comment]
@zetonew please attach `kilosort4.log` from the results directory
