### ISSUE TITLE
Whitening filter removing spikes

### ISSUE THREAD

**Issue by gjin239** [MouseLand/Kilosort#815]
Hi all,

I know Kilosort/Phy is specialised for data with large channel counts, but currently we are only running 4-channel tetrode recordings through this software. As such, the whitening filter appears to be nullifying our valid spikes, even while using low whitening ranges:
(raw VS whitened)
![image](https://github.com/user-attachments/assets/8952ba82-fa57-4e99-a785-569fa671a5f9)
![image](https://github.com/user-attachments/assets/9de43190-6f1d-4a7a-a547-6b9c3668e893)

Is there a way to somehow disable the whitening filter or minimise its effects on our data? Thank you!

**Comment by morales-gregorio** [comment]
Hi @gjin239, 

I think you can still see spikes in the lower figure, just with a much smaller amplitude. Can you z-score the signals in time? 

Whitening removes the correlation between the channels, so the spikes will only remain in whichever channel had the highest amplitude for that spike. Whitening also drastically reduces the amplitude of the whole signal (but not necesarily the ratio between noise and spikes)

**Comment by gjin239** [comment]
Hi @morales-gregorio, thank you for the information on whitening. 

We're more accustomed to using the trace view of KS2, which appears to show that good spikes are sometimes ignored after pre-processing. Not quite sure how to go about z-scoring signals yet: we're trying to reproduce data outputs in KS4, but keep running into a TruncatedSVD ValueError.

**Comment by jacobpennington** [comment]
@gjin239 Can you please upload `kilosort4.log` from the results directory so I can see where you're encountering the error?

**Comment by gjin239** [comment]
@jacobpennington Nothing is saved to the results directory yet, but I can copy-paste the log straight from the message logbox:

```
C:\Users\gjin0008\AppData\Local\anaconda3\envs\kilosort\lib\site-packages\kilosort\io.py:498: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:212.)
  X[:, self.nt : self.nt+nsamp] = torch.from_numpy(data).to(self.device).float()

Preprocessing filters computed in  0.00s; total  0.00s



computing drift


nblocks = 0, skipping drift correction


drift computed in  0.00s; total  0.01s



Extracting spikes using templates


Re-computing universal templates from data.


Traceback (most recent call last):

  File "C:\Users\gjin0008\AppData\Local\anaconda3\envs\kilosort\lib\site-packages\kilosort\gui\sorter.py", line 82, in run

    
st, tF, Wall0, clu0 = detect_spikes(ops, self.device, bfile, tic0=tic0,


  File "C:\Users\gjin0008\AppData\Local\anaconda3\envs\kilosort\lib\site-packages\kilosort\run_kilosort.py", line 392, in detect_spikes

    
st0, tF, ops = spikedetect.run(ops, bfile, device=device, progress_bar=progress_bar)


  File "C:\Users\gjin0008\AppData\Local\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 193, in run

    
ops['wPCA'], ops['wTEMP'] = extract_wPCA_wTEMP(


  File "C:\Users\gjin0008\AppData\Local\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py", line 70, in extract_wPCA_wTEMP

    
model = TruncatedSVD(n_components=ops['settings']['n_pcs']).fit(clips)


  File "C:\Users\gjin0008\AppData\Local\anaconda3\envs\kilosort\lib\site-packages\sklearn\decomposition\_truncated_svd.py", line 209, in fit

    
self.fit_transform(X)


  File "C:\Users\gjin0008\AppData\Local\anaconda3\envs\kilosort\lib\site-packages\sklearn\utils\_set_output.py", line 295, in wrapped

    
data_to_wrap = f(self, X, *args, **kwargs)


  File "C:\Users\gjin0008\AppData\Local\anaconda3\envs\kilosort\lib\site-packages\sklearn\base.py", line 1474, in wrapper

    
return fit_method(estimator, *args, **kwargs)


  File "C:\Users\gjin0008\AppData\Local\anaconda3\envs\kilosort\lib\site-packages\sklearn\decomposition\_truncated_svd.py", line 229, in fit_transform

    
X = self._validate_data(X, accept_sparse=["csr", "csc"], ensure_min_features=2)


  File "C:\Users\gjin0008\AppData\Local\anaconda3\envs\kilosort\lib\site-packages\sklearn\base.py", line 633, in _validate_data

    
out = check_array(X, input_name="X", **check_params)


  File "C:\Users\gjin0008\AppData\Local\anaconda3\envs\kilosort\lib\site-packages\sklearn\utils\validation.py", line 1072, in check_array

    
raise ValueError(


ValueError
: 
Found array with 0 sample(s) (shape=(0, 51)) while a minimum of 1 is required by TruncatedSVD.
```

Just in case they're important, here are the settings I'm currently using, While there are only 4 active channels, as a carry-over from KS2 I've fitted on 12 blank dummy channels such that the data could be read as a Linear x16 probe.
![image](https://github.com/user-attachments/assets/749db839-d84a-4404-89fb-2967c00a24b8)

**Comment by jacobpennington** [comment]
@gjin239 Unfortunately I will need to see the full log, there is a lot more information in there. Please upload it when you are able.

**Comment by gjin239** [comment]
@jacobpennington Turns out I was using an old version of KS4; here's the error log now that I've updated it.
[kilosort4.log](https://github.com/user-attachments/files/17823595/kilosort4.log)

**Comment by jacobpennington** [comment]
I just noticed your comment about concatenating dummy channels. That can cause all sorts of unexpected behavior for Kilosort4. If whitening is removing spikes that are occurring across all channels, the best solution is to concatenate multiple tetrode recordings to be sorted simultaenously, i.e. sort 4 recordings together for 16 channels total (or more).

**Comment by gjin239** [comment]
@jacobpennington Huh, interesting! Is there any chance that 4 recordings would influence each other's sorting outputs? 
(And bonus question: does this apply to both KS4 and earlier versions of KS?)

**Comment by jacobpennington** [comment]
I'm not sure about earlier versions of Kilosort. We're not providing support for those anymore, but you could try asking another user that has sorted tetrode data on previous versions.

As for KS4, sorting the recordings together should not influence sorting results provided that the probe layout is set up correctly. On that note, you sould *not* use the 16-channel linear probe that gets included by default. We use that for some testing, but the contacts for that probe are only spaced 1um apart, which will result in some strange behavior for sorting real data. You should create your own probe map, with channels on the same tetrode spaced close together on the  y-axis (maybe ~20um or so) and a gap of at least ~100um between tetrodes so that they're sorted separately.

**Comment by gjin239** [comment]
@jacobpennington Sounds good, I'll give that a go. 
Just one more question: the raw version of the data we use contains a lot of large-amplitude artifacts. In KS2, we had to crop these out for effective spike detection, causing recordings to have different lengths. Does artifact thresholding (or another preprocessing feature) allow KS4 to automatically remove these large artifacts and make it easier for us to concatenate multiple recordings?

**Comment by jacobpennington** [comment]
There is a parameter for very basic artifact removal, `artifact_threshold`. Any batch containing at least one sample with an absolute value greater than that number will be zeroed out. It's a ham-handed approach that we hope to improve later on, but that's what's there for now. As long as it doesn't end up removing long stretches all at once (i.e. several batches in a row), it seems to work well enough.

**Comment by gjin239** [comment]
@jacobpennington I've created the new file and probe, and now I'm getting a different error: 
[kilosort4.log](https://github.com/user-attachments/files/17892118/kilosort4.log)
Another thing I'm curious about: does the CMR affect anything here at all, and should I be disabling it?
(Thank you for all the information so far, by the way; it's been very insightful!)

**Comment by jacobpennington** [comment]
@gjin239 your batch size is set to the entire duration of the recording, which is going to cause all sorts of problems. As a general rule, you should start by running KS4 without changing any of the parameters from their defaults, except for the sampling rate and number of channels. The default batch size of `60000` should work fine, or `50000` if you want it to be a round number of seconds for your sampling rate. If you run into issues with that (i.e. not enough data per batch because of a low channel count) you can try doubling or tripling that number, but anything more than a ~10 second batch size is well outside the expected range.

**Comment by jacobpennington** [comment]
As for your other question, I don't see any reason why you would need to disable CMR.

**Comment by gjin239** [comment]
@jacobpennington KS4 can run through the entirety of spike sorting now, and the phy outputs are consistent with individual files. Thank you!
However, it currently seems inconsistent for if diagnostic diagrams and phy parameters are saved at all- am I supposed to be clicking the 'run' button multiple times to get all the outputs I need?

**Comment by gjin239** [comment]
@jacobpennington I solved this issue, looks like it just takes a while longer to generate all the phy files because of the data size. Thank you for this information nonetheless, it is useful.

KS4 is currently generating a total of ~12 clusters for a combined dataset, with each cluster clearly consisting of several different merged cells- e.g. these spikes from the same initial identified clusters. 
![image](https://github.com/user-attachments/assets/f8d41c1e-2823-468e-9583-e945af7aa371)
![image](https://github.com/user-attachments/assets/f2a1de49-9167-47fd-b5f0-87daf56816ee)
Is there a setting similar to AUC Split from earlier versions of KS that can be adjusted, or should I keep playing with Th_universal until I reach a happy medium?

**Comment by jacobpennington** [comment]
Changes to `Th_universal` would not directly affect how clusters are merged. If small fluctuations are being detected as spikes but are actually noise, you should increase the threshold. If you're missing spikes at lower amplitudes, decrease the threshold. If you think units are being overmerged or undermerged, you could try tweaking `ccg_threshold`. There's a full list of parameters with their descriptions in `kilosort.parameters.py`, or you can mouse-over the parameter names in the GUI to see the same descriptions.

**Comment by gjin239** [comment]
@jacobpennington I see, thank you. However, it doesn't really seem like tweaking ccg_threshold changes much on my end- would it be because their features are too similar? 
E.g. threshold of 0.5 (1, 15 units detected) VS 0.05 (2, 14 units detected).
(1) ![diagnostics_ccg0 5_600](https://github.com/user-attachments/assets/c167b4f5-7b0b-4fee-ae6a-a1024c764624)
(2) ![diagnostics](https://github.com/user-attachments/assets/fb567f24-6bd4-4ce0-9d9b-7daf4702fe62)

Another query I have is whether KS4 has trouble with certain chunks of data: you can see clearly here that there are two sections where spikes were not detected in any part of the recordings. 
![image](https://github.com/user-attachments/assets/cdddbd67-07e2-4632-8d49-797410072de0)
In the KS4 GUI itself the display appears blank for these sections.
![image](https://github.com/user-attachments/assets/c6678396-f5d5-4b37-8bf4-1dcd28a89d0a)
As in the raw data in these sections are perfectly fine, I was wondering what might be causing these.

**Comment by jacobpennington** [comment]
What does the raw data look like for those sections? The display there is indicating that the values are saturated, usually indicating a recording artifact of some kind (i.e. the values are much higher there than in the rest of the recording).

**Comment by gjin239** [comment]
@jacobpennington That's right, there are artefacts on one of the 4 concatenated files for those sections, but not for the other 3 files. Is there any way for KS4 to focus on spike detection for the other files in the same time period barring manual removal?

An additional question: would designating each of the files onto different kcoords help increase the accuracy of spike detection for each file?

**Comment by jacobpennington** [comment]
No, the only way to prevent those batches from being saturated is to either not include the file with those artefacts (if it's just one of them) or set the `artifact_threshold` parameter to zero out those batches for all 4 files. Specifying kcoords would not help with spike detection for this.

**Comment by gjin239** [comment]
@jacobpennington Filtering out those artifacts not only solved that issue but also ended up helping with spike count detected during sorting.

However, after playing around with concatenated file combinations, it appears that the number of clusters detected for each file vary depending on the combination of files that make up the 16 channels. 
Should I be concerned about this being a sign that spike detection in one file is influenced by other files, despite large probe distances?

**Comment by jacobpennington** [comment]
@gjin239 There shouldn't be any qualitative impact of changing the recording order, but it's possible that it will affect the total number of spikes or clusters found since it will change the initial conditions for the sorting algorithm. In other words, I wouldn't be concerned that the channels are directly influencing each other unless you see evidence of that in the results, but some mua spikes might get clustered together differently (for example) because of the order they're detected in.

**Comment by gjin239** [comment]
@jacobpennington I see, thank you. This is very useful to know.
I've played around with several different ways to filter out artefacts now, but I still consistently get less than 20 clusters, with most clusters being concentrated on the first 4 channels. Is there anything else I could be missing?

**Comment by jacobpennington** [comment]
Is there a reason you expect to find more than 20 clusters? With only 16 channels, that's a reasonable amount to expect to find. If most of them are concentrated on only 4 channels, that might indicate that only one of your tetrodes was detecting good spikes.

**Comment by gjin239** [comment]
@jacobpennington Mostly because of  (1) Phy results for KS4 indicating that some of the clusters can be further split, and (2) KS2 previously being able to detect a similar spread of good spikes along each tetrode, with file 2 having the cleanest spikes instead of file 1.

**Comment by jacobpennington** [comment]
Are you able to share your data?

**Comment by gjin239** [comment]
@jacobpennington Sure, I can share it through email. Which versions would be preferable- the raw Matlab file pre-artefact cleaning or the binary file post-cleaning?

**Comment by jacobpennington** [comment]
The binary file with artifacts removed.

**Comment by jacobpennington** [comment]
Sorry it took so long to get back to you on this. I was able to improve the results a little by tweaking some settings. You can check the screenshot below or use the "Import" button in the GUI to load the settings from the attached .json file.

![Image](https://github.com/user-attachments/assets/ecffd40b-4b52-4dfa-8d2d-4983de0d89c0)

Summary of changes:
* Increased batch size to 1,000,000 samples (40s of data) to help balance the amount of data per batch with the low channel count.
* Set whitening range to 4 so that it applies within each tetrode.
* Set dmin, dminx to 20 to match the spacing declared in the probe file.
* Set nearest chans to 4, nearest templates to 10 to match the number of channels and templates for each tetrode.
* Set nlocks = 0 to disable drift correction.

I got 32 clusters out, and many of those looked pretty good in Phy even if they didn't pass KS4's 'good/mua' checks. Given the tetrode layout and the large number of "blank" sections of data (where artifacts were removed), it's likely Kilosort4 just isn't able to sort the data better than this.

**Comment by gjin239** [comment]
@jacobpennington  No problem at all. Thank you very much for taking the time to sort through the settings! This has been very helpful.
Just one last question to confirm something before I close this thread then: is channel number already factored in regarding spike detections, or will that have to be taken into account separately while analysing data? (E.g. Will I need to divide firing rate by 4 for a cluster detected among 4 channels?)

**Comment by jacobpennington** [comment]
You should not divide the firing rate. Spikes are detected as multi-channel events.

**Comment by gjin239** [comment]
@jacobpennington I think I have everything I need to keep spike sorting now. Thank you for providing all this information and helping with troubleshooting! This has been extremely insightful :)
